sudo: required
env:
  - container_id=$(mktemp) distribution=centos version=7     init=/usr/lib/systemd/systemd
  - container_id=$(mktemp) distribution=ubuntu version=14.04 init=/sbin/init

services:
  - docker

before_install:
  - sudo apt-get update
  # Pull container
  - sudo docker pull ${distribution}:${version}
  # Customize container
  - sudo docker build --rm=true --file=tests/Dockerfile.${distribution} --tag=${distribution}:ansible tests

script:
  #
  # Run test playbook
  #

    # Run container in detached state
  - sudo docker run --detach ${distribution}:ansible "${init}" > "${container_id}"

    # Syntax check
  - sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/test.yml --syntax-check
    # Test role
  - sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/test.yml
    # Idempotence test
  - >
    sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

    # Clean up
  - sudo docker stop "$(cat ${container_id})"

notifications:
  email: false
